wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716770357.111435
    t:
      1:
      - 1
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      2:
      - 1
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      3:
      - 23
      4: 3.8.16
      5: 0.15.4
      8:
      - 5
